# Generated by Django 4.0.2 on 2022-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0003_alter_mydocuments_linkedinurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='projectID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='post',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
