# Generated by Django 4.0.2 on 2022-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0005_remove_application_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='projectID',
            field=models.IntegerField(default=-1),
        ),
    ]
