# Generated by Django 4.0.2 on 2022-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0008_remove_application_chosen_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='applicationStatus',
        ),
        migrations.AddField(
            model_name='application',
            name='offerStatus',
            field=models.CharField(blank=True, choices=[('p', 'Make Decision Later'), ('a', 'Accept'), ('r', 'Reject')], default='p', max_length=50),
        ),
    ]
