# Generated by Django 4.0.2 on 2022-04-18 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0010_post_assigned_alter_application_appdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assigned',
        ),
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
