# Generated by Django 4.0.2 on 2022-04-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0011_remove_post_assigned_post_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'project')},
        ),
    ]
