# Generated by Django 4.0.2 on 2022-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0013_application_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Mark as complete?'),
        ),
    ]
