# Generated by Django 4.0.2 on 2022-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectListing', '0016_post_relatedprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
